- service: compute
  method: "POST"
  path: "/v2.1/servers"
- service: compute
  method: "DELETE"
  path: "/v2.1/servers"
- service: compute
  method: "GET"
  path: "/v2.1/servers"
- service: compute
  method: "GET"
  path: "/v2.1/flavors"
