clouds:
  openstack:
    auth:
      auth_url: https://api.pub1.infomaniak.cloud/identity/v3
      project_domain_name: default
      project_name: PCP-4GXOPDF
      user_domain_name: default
      username: PCU-4GXOPDF
    identity_api_version: 3
    interface: public
    region_name: dc4-a
