apiVersion: v1
kind: ConfigMap
data:
  # Set to "true" using `kubectl` to keep runners around for debugging
  keepRunnersAlive: "false"
  # Set to "true" using `kubectl` to start debugger with scheduler
  runDebugger: "false"
  # Set to "off" using `kubectl` for better debugging experience
  pythonFrozenModules: "on"
  # Set to "true" to keep completed jobs around on runner when debugging
  runnerShallRemoveCompletedJobs: "true"
  runnerLogLevel: "INFO"
metadata:
  name: config-cm