apiVersion: v1
kind: ConfigMap
data:
  # Set to "true" using `kubectl` to keep runners around for debugging
  keepRunnersAlive: "false"
  # Set to "true" using `kubectl` to start debugger with scheduler
  runDebugger: "false"
  # Set to "off" using `kubectl` for better debugging experience
  pythonFrozenModules: "on"
metadata:
  name: config-cm