heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

parameters:
  server_name:
    type: string
    description: VM Name
    constraints:
    - allowed_pattern: "[a-zA-Z0-9-]+"

resources:
  configuration:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        echo "Hello, World" > C:\hi.txt

  windows-server-vm:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_name }
      key_name: windows-keypair
      image: "Windows Server 2019 Standard"
      flavor: a16-ram32-disk80-perf1
      networks: [ "network": ext-net1 ]
      user_data_format: SOFTWARE_CONFIG

  deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: configuration}
      server: {get_resource: windows-server-vm}
